# Generated by Django 5.0.6 on 2024-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.TextField()),
                ('cipher_text', models.TextField()),
                ('key', models.CharField(max_length=30)),
            ],
        ),
    ]
